# Snakemake Profile for SLURM Submission (Using Legacy 'cluster:' for Reliability)

# 1. GENERAL SNAKEMAKE SETTINGS
jobs: 6                       # Max concurrent jobs
use-conda: True
conda-frontend: mamba
latency-wait: 1               # Time (seconds) to wait between job status checks

# CRITICAL: We are removing 'executor: slurm' and 'executor-args' because the modern
# plugin adds the cluster-hostile '--distribution=none' flag.
# By OMITTING the 'executor' and using 'cluster:', we force Snakemake to use the
# reliable legacy submission method with a custom, clean sbatch string.

# 2. SNAKEMAKE RESOURCE DEFAULTS
default-resources:
  slurm_partition: math-alderaan
  runtime: "2880"             # 48 hours in minutes
  mem_mb: 65536                # Default RAM
  threads: 16                 # Default threads

# 3. LEGACY 'cluster:' STRING TEMPLATE (The ONLY part that works on your cluster)
# This explicitly defines the sbatch command, ensuring NO --distribution flag is included.
__default__:
  cluster: "sbatch --partition={resources.slurm_partition} --time={resources.runtime} --mem={resources.mem_mb}M --cpus-per-task={resources.threads} --account=biology-miller-lowry --output=/storage/biology/projects/miller-lowry/beitner/Lowry-assemblies/slurm_logs/rule_{rule}/%j.out --error=/storage/biology/projects/miller-lowry/beitner/Lowry-assemblies/slurm_logs/rule_{rule}/%j.err --mail-type=NONE"